import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "brand-bg": "#121212",
        "brand-surface": "#1A1A1A",
        "brand-blue": "#0044FF",
        "brand-green": "#00D150",
        "brand-red": "#D10000",
        "surface-container-low": "#1c1b1c",
        "surface-container-high": "#2a2a2b",
        "on-tertiary": "#003907",
        "background": "#131314",
        "surface-variant": "#353436",
        "surface-container": "#201f20",
        "inverse-surface": "#e5e2e3",
        "secondary-container": "#0356ff",
        "surface-bright": "#3a393a",
        "inverse-on-surface": "#313031",
        "primary-fixed": "#e7deff",
        "secondary-fixed-dim": "#b6c4ff",
        "on-error": "#690005",
        "error": "#ffb4ab",
        "surface-container-lowest": "#0e0e0f",
        "on-surface": "#e5e2e3",
        "on-secondary": "#002780",
        "on-secondary-fixed-variant": "#0039b3",
        "tertiary-container": "#006b15",
        "on-tertiary-fixed-variant": "#00530e",
        "primary-container": "#6332e5",
        "on-primary-fixed": "#1f0060",
        "on-primary": "#350097",
        "primary": "#ccbdff",
        "on-tertiary-fixed": "#002203",
        "on-secondary-container": "#e4e7ff",
        "inverse-primary": "#6636e8",
        "outline": "#948ea1",
        "tertiary-fixed-dim": "#00e639",
        "secondary-fixed": "#dce1ff",
        "on-error-container": "#ffdad6",
        "secondary": "#b6c4ff",
        "surface-dim": "#131314",
        "error-container": "#93000a",
        "on-secondary-fixed": "#001551",
        "on-background": "#e5e2e3",
        "on-surface-variant": "#cac3d8",
        "primary-fixed-dim": "#ccbdff",
        "surface-tint": "#ccbdff",
        "surface": "#131314",
        "outline-variant": "#494455",
        "on-tertiary-container": "#00f53e",
        "tertiary": "#00e639",
        "tertiary-fixed": "#72ff70",
        "surface-container-highest": "#353436",
        "on-primary-container": "#d9cdff",
        "on-primary-fixed-variant": "#4d03d0"
      },
      fontFamily: {
        "label-caps": ["var(--font-space-mono)", "monospace"],
        "stats-num": ["var(--font-sora)", "sans-serif"],
        "display-lg": ["var(--font-sora)", "sans-serif"],
        "headline-lg": ["var(--font-sora)", "sans-serif"],
        "display-lg-mobile": ["var(--font-sora)", "sans-serif"],
        "headline-sm": ["var(--font-sora)", "sans-serif"],
        "body-lg": ["var(--font-plus-jakarta)", "sans-serif"],
        "body-md": ["var(--font-plus-jakarta)", "sans-serif"],
      },
      spacing: {
        "margin-mobile": "20px",
        "margin-desktop": "48px",
        "stack-sm": "8px",
        "stack-md": "16px",
        "stack-lg": "32px",
        "gutter": "16px",
        "unit": "4px",
      },
    },
  },
  plugins: [],
};
export default config;